# spring configuration
spring:
   application:
      name: webmvc
   
   # devtool
   devtools:
      restart: 
         enabled: true

# server configuration
server:
   port: 8088
   servlet: 
      context-path: /